---
- name: Deploy Elasticsearch ECK Operator and Create an Instance on OCP 4.20
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    ansible_python_interpreter: "{{ lookup('env','VIRTUAL_ENV') + '/bin/python' }}"

  roles:
    - role: .